name: Publish

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  PAGES_UPLOAD: ${{ github.ref == 'refs/heads/main' }}
  MDBOOK_TAG: "v0.4.37"

jobs:
  deploy:
    runs-on: ubuntu-latest

    # GITHUB_TOKEN permissions.
    permissions:
      contents: write  # To push a branch
      pages: write  # To push to a GitHub Pages site
      id-token: write # To update the deployment status

    # Only allow a single concurrent deployment.
    concurrency:
      group: pages
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install mdbook
        run: |
          url="https://github.com/rust-lang/mdbook/releases/download/${MDBOOK_TAG}/mdbook-${MDBOOK_TAG}-x86_64-unknown-linux-gnu.tar.gz"
          mkdir mdbook
          curl -sSL $url | tar -xz --directory=./mdbook
          echo `pwd`/mdbook >> $GITHUB_PATH
      - name: Build Book
        run: mdbook build
      - name: Setup Pages
        if: ${{ env.PAGES_UPLOAD == 'true' }}
        uses: actions/configure-pages@v5
      - name: Upload artifact
        if: ${{ env.PAGES_UPLOAD == 'true' }}
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: 'book'
      - name: Deploy to GitHub Pages
        if: ${{ env.PAGES_UPLOAD == 'true' }}
        id: deployment
        uses: actions/deploy-pages@v4
